### ISSUE TITLE
Pylint engine encountered an error in Codeclimate

### ISSUE THREAD

**Issue by vcalmic** [mercos/codeclimate-pylint#122]
Hello,

The following is my pylint configuration for codeclimate:
```
---
version: "2"
checks:
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 20
plugins:
  pylint:
    enabled: true
    include_paths:
      - 'foobar/'
      - 'tests/'
exclude_patterns:
  - '**/__pycache__/'
  - '**/.pytest_cache/'
```

When running Codeclimate, I received the following error: `engine produced invalid output: {:message=>"Invalid JSON", :output=>"Usage:  pylint [options] modules_or_packages\n\n  Check that module(s) satisfy a coding standard (and more !).\n\n    ` (see the attached file for more)
I tried to execute pylint locally and it worked.

[output.txt](https://github.com/mercos/codeclimate-pylint/files/7802584/output.txt)
